# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{aerial}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Sears"]
  s.date = %q{2009-10-20}
  s.default_executable = %q{aerial}
  s.description = %q{A simple, blogish software build with Sinatra, jQuery, and uses Git for data storage}
  s.email = %q{matt@mattsears.com}
  s.executables = ["aerial"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "aerial.gemspec",
     "bin/aerial",
     "config/config.sample.ru",
     "config/config.sample.yml",
     "config/config.test.yml",
     "config/config.yml",
     "config/deploy.rb",
     "config/thin.sample.yml",
     "examples/articles/congratulations/congratulations-aerial-is-configured-correctly.article",
     "examples/public/javascripts/application.js",
     "examples/public/javascripts/jquery-1.3.1.min.js",
     "examples/public/javascripts/jquery.template.js",
     "examples/views/article.haml",
     "examples/views/articles.haml",
     "examples/views/comment.haml",
     "examples/views/home.haml",
     "examples/views/layout.haml",
     "examples/views/not_found.haml",
     "examples/views/post.haml",
     "examples/views/rss.haml",
     "examples/views/sidebar.haml",
     "examples/views/style.sass",
     "lib/aerial.rb",
     "lib/aerial/app.rb",
     "lib/aerial/article.rb",
     "lib/aerial/build.rb",
     "lib/aerial/base.rb",
     "lib/aerial/config.rb",
     "lib/aerial/content.rb",
     "lib/aerial/installer.rb",
     "spec/aerial_spec.rb",
     "spec/app_spec.rb",
     "spec/article_spec.rb",
     "spec/base_spec.rb",
     "spec/config_spec.rb",
     "spec/fixtures/articles/congratulations-aerial-is-configured-correctly/congratulations-aerial-is-configured-correctly.article",
     "spec/fixtures/articles/sample-article/sample-article.article",
     "spec/fixtures/articles/test-article-one/test-article.article",
     "spec/fixtures/articles/test-article-three/test-article.article",
     "spec/fixtures/articles/test-article-two/comment-missing-fields.comment",
     "spec/fixtures/articles/test-article-two/test-article.article",
     "spec/fixtures/articles/test-article-two/test-comment.comment",
     "spec/fixtures/config.yml",
     "spec/fixtures/public/javascripts/application.js",
     "spec/fixtures/public/javascripts/jquery-1.3.1.min.js",
     "spec/fixtures/public/javascripts/jquery.template.js",
     "spec/fixtures/views/article.haml",
     "spec/fixtures/views/articles.haml",
     "spec/fixtures/views/home.haml",
     "spec/fixtures/views/layout.haml",
     "spec/fixtures/views/not_found.haml",
     "spec/fixtures/views/post.haml",
     "spec/fixtures/views/rss.haml",
     "spec/fixtures/views/sidebar.haml",
     "spec/fixtures/views/style.sass",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/mattsears/aerial}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{aerial}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A simple, blogish software build with Sinatra and uses Git for data storage}
  s.test_files = [
    "spec/aerial_spec.rb",
     "spec/app_spec.rb",
     "spec/article_spec.rb",
     "spec/base_spec.rb",
     "spec/config_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
