---
environment: development
chdir: /apps/aerial
address: 127.0.0.1
port: 4567
pid: /apps/aerial/thin.pid
rackup: /apps/aerial/config.ru
log: /apps/aerial/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: false
servers: 1
